[project]
name = "naver-search-dashboard"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.12"
dependencies = [
    "pandas>=3.0.5",
    "plotly>=7.0.0",
    "python-dotenv>=1.2.3",
    "requests>=2.34.2",
    "streamlit>=1.63.0",
]

[project.scripts]
naver-search-dashboard = "naver_search_dashboard:main"

[build-system]
requires = ["uv_build>=0.12.10,<0.13.0"]
build-backend = "uv_build"
